JS Exercise: Do homework javascript
st-hieucao/internship pull request #10
Opened 2021-10-20 10:52 UTC by st-hieucao

### References
-[Issue URL](https://github.com/st-hieucao/FE-Internship-Winter-2021_-st-hieucao-_FE-Exercise/issues/8)
### Description
-Làm bài tập javascript

2021-10-20 16:21 UTC, st-duynguyen commented on html-exercise/js/home-work.js
> +var mang = [
Đặt tên lại tiếng anh lun em

2021-10-20 16:51 UTC, st-duynguyen commented on html-exercise/js/home-work.js
> +const oddTotals = (arr) => {
function nên đặt là động từ. E check lại mấy thằng dưới lun nha. Ví dụ cái này nếu là a a sẽ đặt là: getOddTotalsInArray

2021-10-20 16:52 UTC, st-duynguyen commented on html-exercise/js/home-work.js
> +const cutString = (string) => {
Function này e đang làm sai đề bài. Nếu dài trên 15 kí tự thì lấy 10 kí tự đầu cộng thêm dấu ... vào

2021-10-20 16:57 UTC, st-duynguyen commented on html-exercise/js/home-work.js
> +  let restCharacter = string.slice(1, string.length);
Thằng này có thể làm đơn giản hơn là: let restCharacter = string.slice(1);

2021-10-20 17:01 UTC, st-duynguyen commented on html-exercise/js/home-work.js
> +const findRepeatNumber = (arr) => {
Bài này e đang hiểu sai đề, cho 2 mảng dữ liệu số tức đầu vào function nào phải là 2 cái mảng

2021-10-20 17:04 UTC, st-duynguyen commented on html-exercise/js/js-exercise.js
> +const sum = (a, b) => {
Tên hàm rõ ra, e đặt như này chưa trình bày được hết tất cả các ý mà function đang có

2021-10-20 17:06 UTC, st-duynguyen commented on html-exercise/js/js-exercise.js
> +const greater19 = (a) => {
tên hàm này tương tự, chưa bao quát được hết tất cả case trong function

2021-10-20 17:07 UTC, st-duynguyen commented on html-exercise/js/js-exercise.js
> +  } else if (a === 19) {
a nghĩ k cần else if này

2021-10-20 17:19 UTC, st-duynguyen commented on html-exercise/js/js-exercise.js
> +const findNumbers = (number, divideNumber) => {
đặt rõ nghĩa tên hàm ra giúp a

2021-10-20 17:35 UTC, st-duynguyen requested changes
Pls check my commentts

2021-10-20 18:42 UTC, st-duynguyen commented on html-exercise/js/home-work.js
> +const capitalizeFirstLetter = (string) => {
e đang khai báo theo cú pháp es6 mất rồi, check lại tất cả chỉ được dùng cú pháp es5 thôi nghe. Ex: var functionName = function (input) {}

2021-10-20 18:44 UTC, st-duynguyen commented
@st-hieucao Check lại code phải dùng syntax của thằng Es5,  e đang dùng toàn bộ của thằng es6 rồi

2021-10-21 07:23 UTC, st-duynguyen commented on html-exercise/js/js-exercise.js
> +    return (19 - a) * 3;
chỗ này phải là a - 19 rồi mới nhân 3 chứ

2021-10-21 13:07 UTC, st-trangnguyen requested changes
Em dùng cú pháp của es5, ko dùng của es6 ví dụ như let, const

2021-10-21 13:07 UTC, st-trangnguyen commented on html-exercise/js/home-work.js
> +    var firstTenCharacter = string.slice(0, 10);
- Ko cần tạo biến mới em, nếu param string em ko cần giữ lại trạng thái ban đầu để làm gì thì cứ dùng thẳng nó string = string.slice(0, 10)
- cộng thêm "..." thì em research thêm hàm concat của js để sử dụng hì

2021-10-21 13:07 UTC, st-trangnguyen commented on html-exercise/js/home-work.js
> +function capitalizeFirstvarter(string) {
- capitalizeFirstvarter => capitalizeFirstLetter
Bài ni làm chi phức tạp ri Hiếu hè, suy nghĩ thêm cách đơn giản hơn nhé

2021-10-21 13:07 UTC, st-trangnguyen commented on html-exercise/js/home-work.js
> +function getMinNumber(arr) {
Bài tập này làm sai rồi em

console.log(getMinNumber([1, 2, 3, 4, 5, 7])) kết quả phải là 1 mới đúng, hiện tại đang là 0

2021-10-22 04:29 UTC, st-duynguyen commented on html-exercise/js/home-work.js
> +    console.log(arr2.indexOf(item) !== -1);
dư log trong này

2021-10-22 04:30 UTC, st-duynguyen commented on html-exercise/js/js-exercise.js
> +const getTotalNumberByEachCase = (a, b) => {
bên này cũng thế, es5 chỉ dùng var chứ k dùng const

2021-10-22 10:17 UTC, st-duynguyen approved these changes
LGTM. But You need fix conflict

2021-10-22 11:08 UTC, st-trangnguyen requested changes
- Fix conflict
- trong file js sử dụng `''` thay vì `""`

2021-10-22 17:20 UTC, st-trangnguyen requested changes
Pull này vẫn còn bị thiếu empty line ở cuối file và dùng "", em check kỹ lại

2021-10-24 08:37 UTC, st-trangnguyen approved these changes

2021-10-24 08:38 UTC, merged