JS Exercise: Do homework javascript ( Day 2 )
st-hieucao/internship pull request #12
Opened 2021-10-21 09:58 UTC by st-hieucao

### References
-[Issue URL](https://github.com/st-hieucao/FE-Internship-Winter-2021_-st-hieucao-_FE-Exercise/issues/11)
### Description
-Làm bài tập javascript (day 2)
![jsday2](https://user-images.githubusercontent.com/92258521/138625969-208fff73-a16e-47c7-80d1-08434fadd973.png)

2021-10-21 13:10 UTC, st-trangnguyen requested changes
chị nghĩ bài tập này em nên tạo folder khác luôn, ko dùng folder `html-excercise` nữa. Vì html, css file bỏ trong `assets/js` ko đúng

2021-10-22 11:28 UTC, st-trangnguyen requested changes

2021-10-22 11:28 UTC, st-trangnguyen commented on js/domExercise.js
> +// ---------------- BAI1
Em phải check window/dom đã load xong chưa rồi mới chạy đống query dom này ko thì dễ bị lỗi

2021-10-24 17:17 UTC, st-duynguyen commented on js/domExercise.js
> +    var input = document.querySelector('.input').value;
chưa có placeholder cho input

2021-10-24 17:19 UTC, st-duynguyen commented
@st-hieucao Thêm screenshot kết quả vào description nữa nha e

2021-10-24 17:19 UTC, st-duynguyen requested changes
Please check my comments

2021-10-24 19:28 UTC, st-trangnguyen requested changes

2021-10-24 19:28 UTC, st-trangnguyen commented on js/domExercise.js
> +  var liElement = document.createElement('li');
liElement là gì chị ko hiểu? element này để làm gì?

2021-10-24 19:28 UTC, st-trangnguyen commented on js/domExercise.js
> +    liElement.append(
Sao lại append cái này tròng vòng for?

2021-10-24 19:28 UTC, st-trangnguyen commented on js/domExercise.js
> +var options = [
Nó là là 1 list plan pricing, ko phải là options

2021-10-24 19:28 UTC, st-trangnguyen commented on js/domExercise.js
> +  if (item.title === 'Basic') {
Tạo 1 thêm attribute trong mỗi plan gọi là `type` basic hoặc pro để check, nếu title nó thay đổi thì sao, hoặc nhiều plan cùng type nhưng khác title thì sao?

2021-10-24 19:28 UTC, st-trangnguyen commented on js/domExercise.js
> +    price: '$10 / month',
Tách 10 và month ra
- 10 là price
- month là interval (plan pricing thường có các interval (chu kì) thanh toán tiền như là month, year, day)....

2021-10-24 19:28 UTC, st-trangnguyen commented on js/domExercise.js
> +    listInfo: [
listInfo => benifits

2021-10-24 19:28 UTC, st-trangnguyen commented on js/index.html
> +<!DOCTYPE html>
Format file

2021-10-24 19:28 UTC, st-trangnguyen commented on js/styles.css
> +* {
Format file

2021-10-24 19:43 UTC, st-trangnguyen commented on js/domExercise.js
> +var listOptionsElement = document.querySelector('.list-options');
Đổi tên mấy element lại cho đúng ngữ nghĩa Hiếu

2021-10-25 03:01 UTC, st-trangnguyen requested changes

2021-10-25 03:01 UTC, st-trangnguyen commented on js/domExercise.js
> +  var formElement = document.createElement('form')
Thiếu `;`

2021-10-25 03:01 UTC, st-trangnguyen commented on js/domExercise.js
> +    priceElement.innerHTML = item.price + '$/month';
Vẫn còn dùng month là reng hè?

2021-10-25 05:17 UTC, st-trangnguyen requested changes

2021-10-25 05:17 UTC, st-trangnguyen commented on js/domExercise.js
> +  inputElement.setAttribute('class', 'input');
Input này nhập chữ đc hả em?

2021-10-25 05:17 UTC, st-trangnguyen commented on js/domExercise.js
> +    priceElement.innerHTML = item.price + '$' + item.interval;
Fix review lại xong đã check lại bài tập còn chạy đúng ko chưa em?

2021-10-25 05:24 UTC, st-trangnguyen commented on js/domExercise.js
> +window.addEventListener('DOMContentLoaded', (event) => {
Gì tới 2 lần gọi event này trong 1 file luôn em?

2021-10-26 09:05 UTC, st-trangnguyen requested changes
Fix hết comments chưa mà request review lại hè??? 2 tuần trôi qua rồi mà nhắc lui nhắc tới 1 vấn đề ni mãi á nghe

2021-10-27 02:32 UTC, st-trangnguyen approved these changes

2021-10-27 02:32 UTC, merged