SCSS Exercise: CSS to SCSS
st-hieucao/internship pull request #7
Opened 2021-10-19 04:10 UTC by st-hieucao

### References
-[Design URL](https://www.figma.com/file/CUQiZbPKOlfjHZn9hBqrPh/Fashion?node-id=0%3A1)
-[Issue URL](https://github.com/st-hieucao/FE-Internship-Winter-2021_-st-hieucao-_FE-Exercise/issues/6)
### Description
-Cấu trúc thư mục stylesheets và chuyển css sang scss.

2021-10-19 15:59 UTC, st-trangnguyen requested changes

2021-10-19 15:59 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/base/_variables.scss
> +
remove dòng này, tránh các line trống ko cần thiết

2021-10-19 15:59 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/base/_variables.scss
> +  primary-color: #fbb03b,
ko cần color phía sau nữa em, primary ko là đủ rồi, các màu khác tương tự

2021-10-19 15:59 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/base/_variables.scss
> +$font-size: (
chị thấy font dùng nhiều nhất là 14 chưa có define?

2021-10-19 15:59 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/layout/_all.scss
> +@import './footer';
add empty line ở cuối file em

2021-10-19 15:59 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/layout/_footer.scss
> +        font-size: 16px;
Define variable font-size ra rồi sao ko dùng em. check ở những chỗ khác

2021-10-19 15:59 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/layout/_grid.scss
> +.row {
số này lặp lại nhiều nên tạo biến cho nó `0.625rem`

2021-10-19 15:59 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/layout/_header.scss
> +  .header-logo {
```
display: flex;
align-items: center;
```
các block code flex box này sẽ gặp đi lặp lại nhiều lần, em dùng các rule của sass để tối ưu tránh lặp code nhiều

2021-10-19 15:59 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/modules/_all.scss
> +@import './btn';
đặt tên file rõ ràng, button

2021-10-19 15:59 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/modules/_btn.scss
> +  &.btn-primary {
gì đây ông

2021-10-22 08:00 UTC, st-trangnguyen requested changes

2021-10-22 08:00 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/base/_all.scss
> +@import './variables';
- Trong css em phải dùng dấu `""` thay vì `''`
- `@import 'variables';` viết vậy cũng import đc rồi, em check tương tự những file khác

2021-10-22 08:00 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/base/_mixin.scss
> +@mixin flex-center{
File này format bị sai nhé

2021-10-22 08:00 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/base/_variables.scss
> +  ls: 16px,
`ls` nghĩa là gì á ông?

2021-10-22 08:00 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/base/_variables.scss
> +  xlg: 19px,
`xlg` là `xl` rồi mà?

2021-10-22 08:00 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/layout/_grid.scss
> +@media screen and (max-width: 480px){
4px bị lặp lại

2021-10-22 08:00 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/layout/_grid.scss
> +  .col-lg-6{
Màn hình nhỏ ko dùng `col-lg` nữa em. Em tham khảo cách build grid cho từng màn hình của bootstrap. Research thêm nhiều vào nhé

2021-10-22 08:00 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/modules/_button.scss
> +}
Chú ý endline, em tập vào github xem file nào còn endline nó sẽ báo đỏ như zậy, fix trc khi chị review

2021-10-22 08:00 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/modules/_card.scss
> +@media screen and (max-width: 480px){
Thiếu space trước `{`, nhiều chỗ bị, em cần check lại kĩ hơn

2021-10-22 08:00 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/modules/_card.scss
> +    .card-name{
nếu ko có style gì khác nữa thì gộp name vs price lại đc nếu nó chung style

2021-10-22 08:00 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/styles.scss
> +@import './state/all';
State phải import trước page em nhé

2021-10-22 14:29 UTC, st-trangnguyen requested changes
Hiếu tự review pull request của mình, check lại toàn vô format, convention, empty line ở cuối file của tất cả file rồi chị review tiếp nhé.

File có endline đúng
![Screen Shot 2021-10-22 at 21 25 43](https://user-images.githubusercontent.com/63229420/138471593-0c18a01c-d1a3-4eea-8d82-3cde9ff6ccda.png)
Files có endline sai
![Screen Shot 2021-10-22 at 21 25 31](https://user-images.githubusercontent.com/63229420/138471618-f8a7081f-3256-4a80-8f93-63a24bf21b31.png)
![Screen Shot 2021-10-22 at 21 25 24](https://user-images.githubusercontent.com/63229420/138471622-83913b4b-2341-46fe-8611-a7586dd1e093.png)

2021-10-22 15:27 UTC, st-trangnguyen requested changes

2021-10-22 15:27 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/layout/_footer.scss
> +        font-family: Helvetica;
Define variable cho font

2021-10-22 15:27 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/layout/_footer.scss
> +        padding: 0 0.625rem;
Cái này em sửa lại padding của container chứ ko phải đi sửa padding của từng section

2021-10-22 15:27 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/layout/_grid.scss
> +.col-2 {
Dùng `for loop` của sass để build grid. build hết tất cả các loại col

2021-10-22 15:27 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/layout/_grid.scss
> +  padding: 0 map-get($space, "desk");
Tại sao phải add cho từng cái như vậy
Em search thêm và dùng css selector https://www.w3schools.com/cssref/sel_attr_begin.asp

2021-10-22 15:27 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/layout/_grid.scss
> +    margin: 0 -4px;
Tại sao vẫn dùng `4px` cứng ở đây mà ko phải là dùng variable?

2021-10-22 15:27 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/layout/_header.scss
> +  .header-logo {
check comment này em nhé

2021-10-22 15:27 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/modules/_card.scss
> +  &::after {
Đoạn code tạo layer này giống nhau ở nhiều chỗ, em dùng mixin để tái sử dụng

2021-10-22 15:27 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/pages/_home.scss
> +        @include flex-center;
@include/@extend luôn luôn nằm trên cùng

2021-10-22 15:27 UTC, st-trangnguyen commented on html-exercise/index.html
> +</html>
Còn sót 1 file -_-

2021-10-23 10:44 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/modules/_card.scss
> +  &::after {
Ý chị là đoạn code của phần after này nè em

2021-10-23 10:53 UTC, st-trangnguyen requested changes

2021-10-23 10:53 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/base/_mixin.scss
> +@mixin layer-100 {
Cái này có gì đâu mà tạo mixin, ý chị là đoạn code phần :after để tạo layer

2021-10-23 10:53 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/base/_mixin.scss
> +@mixin layer-w-100 {
Tên mixin này hơi khó hiểu, nhưng chị thấy cái ngày ko cần thiết phải tạo mixin

2021-10-23 10:53 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/base/_variables.scss
> +$grid-columns: 12;
Biến này em có thể khai báo trong file grid để dễ nhìn hơn

2021-10-23 10:53 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/layout/_grid.scss
> +  margin: 0 -0.625rem;
Có define variable cho `0.625rem` sao ko dùng em?

2021-10-23 10:53 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/layout/_grid.scss
> +  @for $i from 1 through $grid-columns {
2 vòng for này lặp nhau em nên dùng mixin

2021-10-23 10:53 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/modules/_button.scss
> +  border-radius: 2.063rem;
Border ko cần dùng rem đâu em

2021-10-23 15:21 UTC, st-trangnguyen requested changes

2021-10-23 15:21 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/base/_mixin.scss
> +@mixin layer {
Cái mixin này chị thấy em chưa làm đc gì để tái sử dụng hết. Nếu em ko bik đc cách tái sử dụng cho những đoạn code giống nhau thì có thể ko cần tạo mixin này luôn

2021-10-23 15:21 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/layout/_grid.scss
> +$grid-columns: 12;
Tạo mà ko dùng tạo làm gì em

2021-10-23 15:21 UTC, st-trangnguyen commented on html-exercise/index.html
> +                <li class="collection-item h-100 col-6 col-sm-6">
Nếu giữa các màn hình col ko thay đổi thì chỉ cần sử dụng class cho col thôi

2021-10-24 01:51 UTC, st-hieucao commented on html-exercise/index.html
> +                <li class="collection-item h-100 col-6 col-sm-6">
Chỗ này em chưa rõ cho lắm. Do cái mixin của em nó check sizeScreen truyền vào là '' hay 'sm' để tạo grid-system cho desk hay mobile, nên nếu xóa class col-sm-6 đi thì ở mobile padding vẫn là 10px á chị. 

![image](https://user-images.githubusercontent.com/92258521/138576814-70cf7d03-2322-45fb-b460-3f29548fa33a.png)
![image](https://user-images.githubusercontent.com/92258521/138576820-e57f3c52-9a41-41ba-b6eb-785a98a1654c.png)

2021-10-24 08:27 UTC, st-trangnguyen commented on html-exercise/assets/stylesheets/base/_mixin.scss
> +@mixin create-layer {
Cái layer này quan trọng nhất background như thế nào, thì lần sau em nên tạo 1 mixin nhận vào param có background, opacity bao nhiêu. Width-height khác nhau có thể style thằng ở element

2021-10-24 08:33 UTC, st-trangnguyen reviewed
Chị tạm approve pull này, Em cần tìm hiểu nhiều thêm về sass, cách sử dụng grid,....

2021-10-24 08:33 UTC, st-trangnguyen approved these changes

2021-10-24 08:33 UTC, merged